apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      name: laravel-app
  template:
    metadata:
      labels:
        name: laravel-app
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - name: app-container
          image: laravel-app:latest
          # image: gcr.io/ambi-valinor-ds/laravel-app:latest
          imagePullPolicy: Always
          resources: {}
          # ports:
          #   - containerPort: 9000
        - name: nginx-container
          image: nginx
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config-volume
              subPath: nginx.conf
          ports:
            - containerPort: 80
