version: "2.4"

services:

  server:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./dev-services/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_started

  php:
    build: 
      context: .
      dockerfile: dev-services/php.dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
        - ./src:/var/www/html:delegated

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      interval: 2s
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/3306"]


  ## UTILITIES composer, npm & artisan    
  composer:
    build: 
      context: .
      dockerfile: dev-services/composer.dockerfile
    volumes:
      - ./src:/var/www/html

  npm:
    image: node:14
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]

  artisan:
    build:
      context: .
      dockerfile: dev-services/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

