version: "2.4"

services:

  server:
    build:
      context: .
      dockerfile: opt/docker/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./opt/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      fpm:
        condition: service_started

  fpm:
    build: 
      context: .
      dockerfile: opt/docker/fpm/Dockerfile
    depends_on:
      db:
        # condition: service_healthy
        condition: service_started
    volumes:
        - .:/var/www/html

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      interval: 2s
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/3306"]


  ## UTILITIES composer, npm & artisan    
  npm:
    image: node:14
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: ["npm"]
