apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel
data:
  APP_NAME: laravel
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://localhost:8080
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: mariadb
  DB_PORT: "3306"
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: laravel
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  # MAIL_MAILER: smtp
  # MAIL_HOST: smtp.mailtrap.io
  # MAIL_PORT: "2525"
  # MAIL_USERNAME: 972f006c1cc75c
  # MAIL_PASSWORD: 6c727555190e21
  # MAIL_ENCRYPTION: tls
  # PROMETHEUS_NAMESPACE: default
  # PROMETHEUS_METRICS_ROUTE_ENABLED: "true"
  # PROMETHEUS_METRICS_ROUTE_PATH: metrics
  # PROMETHEUS_METRICS_ROUTE_MIDDLEWARE: "null"
  # PROMETHEUS_STORAGE_ADAPTER: memory
  # REDIS_HOST: redis-master
  # REDIS_PORT: "6379"
  # PROMETHEUS_REDIS_PREFIX: PROMETHEUS_
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
          listen  80 default_server;
          listen [::]:80 default_server;

          root /var/www/html;

          index /public/index.php;
          error_page 404 /public/index.php;

          location / {
              try_files $uri $uri/ /public/index.php;
          }

          location ~ \.php$ {
              fastcgi_pass localhost:9000;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param SCRIPT_NAME $fastcgi_script_name;
          }
      }
    }