apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx
      containers:
        - name: php-fpm
          image: jacob:build
          resources: {}
          ports:
            - containerPort: 9000
        - name: nginx
          image: nginx
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-config
              subPath: default.conf
          ports:
            - containerPort: 80
