version: "2.4"

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./opt/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_started

  php:
    build:
      target: base
      context: .
    working_dir: /var/www/html
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app-database
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      interval: 2s
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
