apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      name: app-name
  template:
    metadata:
      labels:
        name: app-name
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - name: app-container
          image: jacob:build
          resources: {}
          # ports:
          #   - containerPort: 9000
        - name: nginx-container
          image: nginx
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config-volume
              subPath: nginx.conf
          ports:
            - containerPort: 80
