apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
          listen         80 default_server;
          listen         [::]:80 default_server;
          root           /var/www/html;

          location / {
              try_files $uri $uri/ /public/index.php;
          }

          location ~ \.php$ {
              fastcgi_pass    localhost:9000;
              include         fastcgi_params;
              fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
              fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
          }
      }
    }
